pub mod crp;
pub mod table;
pub(crate) mod mvn;
pub(crate) mod multivariate_t;
pub(crate) mod niw;
pub mod stream_crp;
pub mod batch_crp;
pub mod projection;
// pub mod conditional;
pub(crate) mod util;
